- name: Shoal Host Setup
  hosts: k3s_cluster
  become: true
  serial: 6
  roles:
    - basic-setup

- name: Cluster prep
  hosts: k3s_cluster
  become: true
  serial: 6
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Shoal K3S Server Setup (Raspberry)
  hosts: server
  become: true
  serial: 6
  tasks:
    - include_role:
        name: basic-setup-rpi
      when: cluster_type == "raspberry"
    - include_role:
        name: haproxy-keepalived
      when: cluster_type == "raspberry"

- name: Shoal K3S Server Setup (Oracle)
  hosts: server
  serial: 6
  tasks:
    - include_role:
        name: basic-setup-oracle
      when: cluster_type == "oracle"

- name: Setup K3S server
  hosts: server
  become: true
  serial: 6
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  serial: 6
  roles:
    - role: k3s_agent

- name: Get config
  hosts: server[0]
  become: true
  roles:
    - role: k3s_post